#!/bin/bash

mkdir /opt/jenkins
yum install -y java-21
ssh-keygen -f /root/.ssh/slavekeys -N ""
echo $(cat /root/.ssh/slavekeys.pub) >> /root/.ssh/authorized_keys
dnf -y install dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
yum install -y docker
